defaults:
- scope:
    path: ""
  values:
    lang: "en"

- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

- scope:
    path: ""
    type: "posts"
  values:
    layout:     "post"
    date_fmt:   "%F"
    categories: "news"
    comments:   false

exclude:
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- Gemfile
- Gemfile.lock
- LICENSE
- new_post
- node_modules
- package.json
- package-lock.json
- README.md
- setup.sh
- assets/css/style.css
- TODO.md
- yarn.lock
- yarn-error.log

plugins:
- jekyll-sitemap
- jemoji

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

name: "SFZTools"
url: "https://sfztools.github.io"

repository:
  owner_url: "https://github.com/sfztools"
  name:      "sfztools.github.io"
  branch:    "master"

locale:
  default: "en"

authors:
  content: "Paul Ferrand"
  web: "RedTide"

copyright: "SFZTools Organization"

realfavicongenerator:
  mask_icon_color: "#000000"
  msapplication_tile_color: "#ffffff"
  theme_color: "#ffffff"
