defaults:
- scope:
    path: ""
  values:
    lang: "en"

- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

- scope:
    path: ""
    type: "posts"
  values:
    layout:     "post"
    date_fmt:   "%F"
    categories: "news"
    comments:   false

exclude:
- gnuplot-src/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- assets/css/style.css
- Gemfile
- Gemfile.lock
- LICENSE
- new_post
- node_modules
- package.json
- package-lock.json
- README.md
- setup.sh
- sfztools.code-workspace
- yarn.lock
- yarn-error.log
- mkdocs/
- mkdocs.sh
- mkdocs.yml
- poetry.lock
- pyproject.toml

plugins:
- jekyll-sitemap
- jemoji

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

name: "SFZTools"
url: "https://sfztools.github.io"

repository:
  owner_url: "https://github.com/sfztools"
  name:      "sfztools.github.io"
  branch:    "master"

locale:
  default: "en"

authors:
  content: "SFZTools Organization"
  web: "SFZTools Organization"

copyright: "SFZTools Organization"

realfavicongenerator:
  mask_icon_color: "#000000"
  msapplication_tile_color: "#ffffff"
  theme_color: "#ffffff"
