docs_dir:         "docs"
site_dir:         "_site"
site_name:        "SFZTools"
site_author:      "SFZTools Organization"
site_description: "SFZTools Website"
site_url:         "https://sfz.tools"
repo_url:         "https://github.com/sfztools/sfztools.github.io"
edit_uri:         "edit/master/docs/"
remote_branch:    "www"
repo_name:        "GitHub"
extra:
  site_since:      2019
  site_web_author: "SFZTools Organization"
  show_copyright:  true
  show_logo:       true
  show_name:       true
  repo_owner_url:  "https://github.com/sfztools"
  repo_branch:     "master"
  data:
    layout:
      cards: "data/layout/cards.yml"
      nav:   "data/layout/navigation.yml"
    sfizz:
      api:
        message:   "data/sfizz/api/sfizz_message.h.json"
        sfizz_h:   "data/sfizz/api/sfizz.h.json"
        sfizz_hpp: "data/sfizz/api/sfizz.hpp.json"
      support:     "data/sfizz/support.yml"
    sfz:           "data/sfz/syntax.yml"
extra_css:
- "assets/css/fontawesome.min.css"
- "assets/css/brands.min.css"
- "assets/css/solid.min.css"
- "assets/css/v4-font-face.min.css"
- "assets/css/bootstrap-table.min.css"
extra_javascript:
- "assets/js/bootstrap-table.min.js"
- "assets/js/mermaid.min.js"
hooks:
- "scripts/hooks/fs.py"
- "scripts/hooks/gh_emojis.py"
- "scripts/hooks/sfizz.py"
markdown_extensions:
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_png
    alt: "short"
    options:
      attributes:
        align:  "absmiddle"
        height: "20px"
        width:  "20px"
plugins:
  search: {}
# FIXME: conflicts with # prefixed HTML unicode characters, see
#        https://github.com/theskumar/autolink-references-mkdocs-plugin/issues/7
# autolink_references:
#   autolinks:
#   - reference_prefix: '#'
#     target_url: "https://github.com/sfztools/sfizz/issues/<num>"
  blogging:
    dirs:
    - "news/posts"
    locale: "en"
    full_content: true
    paging: true
    show_total: false
    size: 5
    template: "layout/blogging-plugin.j2"
    meta_time_format: "%Y-%m-%dT%H:%M:%S%z"
    time_format: "%Y-%m-%d %H:%M:%S"
  exclude: # TODO: to remove when 1.5 comes out
    glob:
    - "docs/templates"
    - "*.j2"
  gen-files:
    scripts:
    - scripts/generators/atom_feed.py
    - scripts/generators/svg_badge.py
# include_dir_to_nav: {}
  macros:
    include_yaml:
    - sfizz_hpp:            "data/sfizz/api/sfizz.hpp.json"
    - sfizz_h:              "data/sfizz/api/sfizz.h.json"
    - sfizz_message_h:      "data/sfizz/api/sfizz_message.h.json"
    - sfizz_release:        "data/sfizz/release.yml"
    # TODO: data for both documentation and layout/theme?
    - sfizz_support_macros: "data/sfizz/support.yml"
    - sfz_syntax_macros:    "data/sfz/syntax.yml"
    include_dir:            "macros/includes"
  # module_name:            "macros/module"
    verbose: true
theme:
  name:        null
  custom_dir: "layout"
  highlightjs: true
  hljs_light: "github"
  hljs_dark:  "github-dark-dimmed"
  nav_style:  "dark"
  locale:     "en"
  bootstrap_version: "5.3.0"
  favicons:
    apple_touch_icon_size: "180x180"
    msapp_tilecolor: "#ffffff"
    theme_color: "#ffffff"
  shortcuts:
    help:     191 # ?
    next:      78 # n
    previous:  80 # p
    search:    83 # s
watch:
- "data"
- "docs"
- "macros/includes"
- "layout"
